# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 273)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LoadImageButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.LoadImageButton1.setGeometry(QtCore.QRect(30, 50, 101, 23))
        self.LoadImageButton1.setObjectName("LoadImageButton1")
        self.ImageText1 = QtWidgets.QLabel(self.centralwidget)
        self.ImageText1.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.ImageText1.setObjectName("ImageText1")
        self.LoadImageButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.LoadImageButton2.setGeometry(QtCore.QRect(30, 130, 101, 23))
        self.LoadImageButton2.setObjectName("LoadImageButton2")
        self.ImageText2 = QtWidgets.QLabel(self.centralwidget)
        self.ImageText2.setGeometry(QtCore.QRect(30, 160, 111, 16))
        self.ImageText2.setObjectName("ImageText2")
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setGeometry(QtCore.QRect(160, 30, 151, 191))
        self.groupBox1.setObjectName("groupBox1")
        self.pushButton_1_1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_1_1.setGeometry(QtCore.QRect(10, 30, 131, 23))
        self.pushButton_1_1.setObjectName("pushButton_1_1")
        self.pushButton_1_2 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_1_2.setGeometry(QtCore.QRect(10, 70, 131, 23))
        self.pushButton_1_2.setObjectName("pushButton_1_2")
        self.pushButton_1_3 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_1_3.setGeometry(QtCore.QRect(10, 110, 131, 23))
        self.pushButton_1_3.setObjectName("pushButton_1_3")
        self.pushButton_1_4 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_1_4.setGeometry(QtCore.QRect(10, 150, 131, 23))
        self.pushButton_1_4.setObjectName("pushButton_1_4")
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setGeometry(QtCore.QRect(340, 30, 151, 191))
        self.groupBox2.setObjectName("groupBox2")
        self.pushButton_2_1 = QtWidgets.QPushButton(self.groupBox2)
        self.pushButton_2_1.setGeometry(QtCore.QRect(10, 40, 131, 23))
        self.pushButton_2_1.setObjectName("pushButton_2_1")
        self.pushButton_2_2 = QtWidgets.QPushButton(self.groupBox2)
        self.pushButton_2_2.setGeometry(QtCore.QRect(10, 90, 131, 23))
        self.pushButton_2_2.setObjectName("pushButton_2_2")
        self.pushButton_2_3 = QtWidgets.QPushButton(self.groupBox2)
        self.pushButton_2_3.setGeometry(QtCore.QRect(10, 140, 131, 23))
        self.pushButton_2_3.setObjectName("pushButton_2_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2022 Opencvdl Hw1"))
        self.LoadImageButton1.setText(_translate("MainWindow", "Load Image 1"))
        self.ImageText1.setText(_translate("MainWindow", "No image loaded"))
        self.LoadImageButton2.setText(_translate("MainWindow", "Load Image 2"))
        self.ImageText2.setText(_translate("MainWindow", "No image loaded"))
        self.groupBox1.setTitle(_translate("MainWindow", "1. Image Processing"))
        self.pushButton_1_1.setText(_translate("MainWindow", "1.1 Color Seperation"))
        self.pushButton_1_2.setText(_translate("MainWindow", "1.2 Color Transform"))
        self.pushButton_1_3.setText(_translate("MainWindow", "1.3 Color Detection"))
        self.pushButton_1_4.setText(_translate("MainWindow", "1.4 Blending"))
        self.groupBox2.setTitle(_translate("MainWindow", "2. Image Smoothing"))
        self.pushButton_2_1.setText(_translate("MainWindow", "2.1 Gaussian Blur"))
        self.pushButton_2_2.setText(_translate("MainWindow", "2.2  Bilateral Filter"))
        self.pushButton_2_3.setText(_translate("MainWindow", "2.3 Median Filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
