# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(513, 435)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LoadImageButton = QtWidgets.QPushButton(self.centralwidget)
        self.LoadImageButton.setGeometry(QtCore.QRect(40, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.LoadImageButton.setFont(font)
        self.LoadImageButton.setObjectName("LoadImageButton")
        self.ImageText = QtWidgets.QLabel(self.centralwidget)
        self.ImageText.setGeometry(QtCore.QRect(40, 200, 111, 16))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.ImageText.setFont(font)
        self.ImageText.setObjectName("ImageText")
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setGeometry(QtCore.QRect(260, 30, 211, 341))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.groupBox1.setFont(font)
        self.groupBox1.setObjectName("groupBox1")
        self.pushButton_1_1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_1_1.setGeometry(QtCore.QRect(20, 40, 171, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.pushButton_1_1.setFont(font)
        self.pushButton_1_1.setObjectName("pushButton_1_1")
        self.pushButton_1_2 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_1_2.setGeometry(QtCore.QRect(20, 100, 171, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.pushButton_1_2.setFont(font)
        self.pushButton_1_2.setObjectName("pushButton_1_2")
        self.pushButton_1_3 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_1_3.setGeometry(QtCore.QRect(20, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.pushButton_1_3.setFont(font)
        self.pushButton_1_3.setObjectName("pushButton_1_3")
        self.pushButton_1_4 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_1_4.setGeometry(QtCore.QRect(20, 220, 171, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.pushButton_1_4.setFont(font)
        self.pushButton_1_4.setObjectName("pushButton_1_4")
        self.pushButton_1_5 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_1_5.setGeometry(QtCore.QRect(20, 280, 171, 31))
        font = QtGui.QFont()
        font.setFamily("新細明體")
        font.setPointSize(10)
        self.pushButton_1_5.setFont(font)
        self.pushButton_1_5.setObjectName("pushButton_1_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 513, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2022 Opencvdl Hw2"))
        self.LoadImageButton.setText(_translate("MainWindow", "Load Image"))
        self.ImageText.setText(_translate("MainWindow", "No image loaded"))
        self.groupBox1.setTitle(_translate("MainWindow", "5. ResNet50"))
        self.pushButton_1_1.setText(_translate("MainWindow", "1. Show Images"))
        self.pushButton_1_2.setText(_translate("MainWindow", "2. Show Distribution"))
        self.pushButton_1_3.setText(_translate("MainWindow", "3. Show Model Structure"))
        self.pushButton_1_4.setText(_translate("MainWindow", "4. Show Comparison"))
        self.pushButton_1_5.setText(_translate("MainWindow", "5. Inference"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
